INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (1, 1, 'Afghanistan', '', '/images/afghanistan.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (2, 1, 'Albania', '', '/images/albania.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (3, 1, 'Algeria', '', '/images/algeria.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (4, 1, 'Andorra', '', '/images/andorra.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (5, 1, 'Angola', '', '/images/angola.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (6, 1, 'Antigua and Barbuda', '', '/images/antigua_and_barbuda.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (7, 1, 'Argentina', '', '/images/argentina.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (8, 1, 'Armenia', '', '/images/armenia.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (9, 1, 'Australia', 'Úc', '/images/australia.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (10, 1, 'Austria', 'Áo', '/images/austria.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (11, 1, 'Azerbaijan', '', '/images/azerbaijan.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (12, 1, 'The Bahamas', '', '/images/the_bahamas.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (13, 1, 'Bahrain', '', '/images/bahrain.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (14, 1, 'Bangladesh', '', '/images/bangladesh.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (15, 1, 'Barbados', '', '/images/barbados.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (16, 1, 'Belarus', '', '/images/belarus.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (17, 1, 'Belgium', 'Bỉ', '/images/belgium.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (18, 1, 'Belize', '', '/images/belize.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (19, 1, 'Benin', '', '/images/benin.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (20, 1, 'Bhutan', '', '/images/bhutan.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (21, 1, 'Bolivia', '', '/images/bolivia.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (22, 1, 'Bosnia and Herzegovina', '', '/images/bosnia_and_herzegovina.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (23, 1, 'Botswana', '', '/images/botswana.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (24, 1, 'Brazil', '', '/images/brazil.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (25, 1, 'Brunei', '', '/images/brunei.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (26, 1, 'Bulgaria', '', '/images/bulgaria.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (27, 1, 'Burkina Faso', '', '/images/burkina_faso.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (28, 1, 'Burundi', '', '/images/burundi.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (29, 1, 'Cambodia', 'Campuchia', '/images/cambodia.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (30, 1, 'Cameroon', '', '/images/cameroon.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (31, 1, 'Canada', '', '/images/canada.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (32, 1, 'Cape Verde', '', '/images/cape_verde.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (33, 1, 'Central African Republic', 'Cộng hòa Trung Phi', '/images/central_african_republic.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (34, 1, 'Chad', '', '/images/chad.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (35, 1, 'Chile', '', '/images/chile.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (36, 1, 'China', 'Trung Quốc', '/images/china.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (37, 1, 'Colombia', '', '/images/colombia.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (38, 1, 'Comoros', '', '/images/comoros.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (39, 1, 'Democratic Republic of the Congo', 'Cộng hòa Dân chủ Congo', '/images/democratic_republic_of_the_congo.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (40, 1, 'Republic of the Congo', 'Cộng hòa Congo', '/images/republic_of_the_congo.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (41, 1, 'Costa Rica', '', '/images/costa_rica.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (42, 1, 'Croatia', '', '/images/croatia.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (43, 1, 'Cuba', '', '/images/cuba.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (44, 1, 'Cyprus', 'Síp', '/images/cyprus.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (45, 1, 'Czech Republic', 'Cộng hòa Séc', '/images/czech_republic.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (46, 1, 'Denmark', 'Đan Mạch', '/images/denmark[i].png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (47, 1, 'Djibouti', '', '/images/djibouti.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (48, 1, 'Dominica', '', '/images/dominica.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (49, 1, 'Dominican Republic', 'Cộng hòa Dominica', '/images/dominican_republic.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (50, 1, 'Ecuador', '', '/images/ecuador.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (51, 1, 'Egypt', 'Ai Cập', '/images/egypt.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (52, 1, 'El Salvador', '', '/images/el_salvador.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (53, 1, 'Equatorial Guinea', '', '/images/equatorial_guinea.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (54, 1, 'Eritrea', '', '/images/eritrea.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (55, 1, 'Estonia', '', '/images/estonia.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (56, 1, 'Eswatini', '', '/images/eswatini.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (57, 1, 'Ethiopia', '', '/images/ethiopia.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (58, 1, 'Fiji', '', '/images/fiji.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (59, 1, 'Finland', 'Phần Lan', '/images/finland.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (60, 1, 'France', 'Pháp', '/images/france.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (61, 1, 'Gabon', '', '/images/gabon.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (62, 1, 'The Gambia', '', '/images/the_gambia.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (63, 1, 'Georgia', '', '/images/georgia.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (64, 1, 'Germany', 'Đức', '/images/germany.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (65, 1, 'Ghana', '', '/images/ghana.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (66, 1, 'Greece', 'Hy Lạp', '/images/greece.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (67, 1, 'Grenada', '', '/images/grenada.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (68, 1, 'Guatemala', '', '/images/guatemala.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (69, 1, 'Guinea', '', '/images/guinea.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (70, 1, 'Guinea-Bissau', '', '/images/guinea-bissau.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (71, 1, 'Guyana', '', '/images/guyana.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (72, 1, 'Haiti', '', '/images/haiti.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (73, 1, 'Honduras', '', '/images/honduras.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (74, 1, 'Hungary', '', '/images/hungary.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (75, 1, 'Iceland', '', '/images/iceland.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (76, 1, 'India', 'Ấn Độ', '/images/india.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (77, 1, 'Indonesia', '', '/images/indonesia.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (78, 1, 'Iran', '', '/images/iran.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (79, 1, 'Iraq', '', '/images/iraq.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (80, 1, 'Ireland', '', '/images/ireland.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (81, 1, 'Israel', '', '/images/israel.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (82, 1, 'Italy', 'Ý', '/images/italy.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (83, 1, 'Ivory Coast', 'Bờ Biển Ngà', '/images/ivory_coast.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (84, 1, 'Jamaica', '', '/images/jamaica.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (85, 1, 'Japan', 'Nhật Bản', '/images/japan.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (86, 1, 'Jordan', '', '/images/jordan.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (87, 1, 'Kazakhstan', '', '/images/kazakhstan.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (88, 1, 'Kenya', '', '/images/kenya.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (89, 1, 'Kiribati', '', '/images/kiribati.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (90, 1, 'Kuwait', '', '/images/kuwait.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (91, 1, 'Kyrgyzstan', '', '/images/kyrgyzstan.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (92, 1, 'Laos', 'Lào', '/images/laos.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (93, 1, 'Latvia', '', '/images/latvia.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (94, 1, 'Lebanon', '', '/images/lebanon.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (95, 1, 'Lesotho', '', '/images/lesotho.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (96, 1, 'Liberia', '', '/images/liberia.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (97, 1, 'Libya', '', '/images/libya.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (98, 1, 'Liechtenstein', '', '/images/liechtenstein.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (99, 1, 'Lithuania', '', '/images/lithuania.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (100, 1, 'Luxembourg', '', '/images/luxembourg.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (101, 1, 'Madagascar', '', '/images/madagascar.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (102, 1, 'Malawi', '', '/images/malawi.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (103, 1, 'Malaysia', '', '/images/malaysia.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (104, 1, 'Maldives', '', '/images/maldives.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (105, 1, 'Mali', '', '/images/mali.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (106, 1, 'Malta', '', '/images/malta.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (107, 1, 'Marshall Islands', 'Quần đảo Marshall', '/images/marshall_islands.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (108, 1, 'Mauritania', '', '/images/mauritania.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (109, 1, 'Mauritius', '', '/images/mauritius.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (110, 1, 'Mexico', '', '/images/mexico.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (111, 1, 'Micronesia', '', '/images/micronesia.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (112, 1, 'Moldova', '', '/images/moldova.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (113, 1, 'Monaco', '', '/images/monaco.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (114, 1, 'Mongolia', 'Mông Cổ', '/images/mongolia.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (115, 1, 'Montenegro', '', '/images/montenegro.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (116, 1, 'Morocco', 'Ma-rốc', '/images/morocco.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (117, 1, 'Mozambique', '', '/images/mozambique.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (118, 1, 'Myanmar', '', '/images/myanmar.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (119, 1, 'Namibia', '', '/images/namibia.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (120, 1, 'Nauru', '', '/images/nauru.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (121, 1, 'Nepal', '', '/images/nepal.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (122, 1, 'Netherlands', 'Hà Lan', '/images/netherlands.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (123, 1, 'New Zealand', '', '/images/new_zealand.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (124, 1, 'Nicaragua', '', '/images/nicaragua.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (125, 1, 'Niger', '', '/images/niger.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (126, 1, 'Nigeria', '', '/images/nigeria.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (127, 1, 'North Korea', 'Bắc Triều Tiên', '/images/north_korea.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (128, 1, 'North Macedonia', 'Bắc Macedonia', '/images/north_macedonia.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (129, 1, 'Norway', 'Na Uy', '/images/norway.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (130, 1, 'Oman', '', '/images/oman.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (131, 1, 'Pakistan', '', '/images/pakistan.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (132, 1, 'Palau', '', '/images/palau.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (133, 1, 'Palestine', '', '/images/palestine.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (134, 1, 'Panama', '', '/images/panama.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (135, 1, 'Papua New Guinea', '', '/images/papua_new_guinea.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (136, 1, 'Paraguay', '', '/images/paraguay.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (137, 1, 'Peru', '', '/images/peru.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (138, 1, 'Philippines', '', '/images/philippines.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (139, 1, 'Poland', 'Ba Lan', '/images/poland.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (140, 1, 'Portugal', 'Bồ Đào Nha', '/images/portugal.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (141, 1, 'Qatar', '', '/images/qatar.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (142, 1, 'Romania', '', '/images/romania.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (143, 1, 'Russia', 'Nga', '/images/russia.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (144, 1, 'Rwanda', '', '/images/rwanda.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (145, 1, 'Saint Kitts and Nevis', '', '/images/saint_kitts_and_nevis.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (146, 1, 'Saint Lucia', '', '/images/saint_lucia.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (147, 1, 'Saint Vincent and the Grenadines', '', '/images/saint_vincent_and_the_grenadines.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (148, 1, 'Samoa', '', '/images/samoa.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (149, 1, 'San Marino', '', '/images/san_marino.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (150, 1, 'São Tomé and Príncipe', '', '/images/São Tomé and Príncipe.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (151, 1, 'Saudi Arabia', 'Ả-Rập Xê-út', '/images/saudi_arabia.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (152, 1, 'Senegal', '', '/images/senegal.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (153, 1, 'Serbia', '', '/images/serbia.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (154, 1, 'Seychelles', '', '/images/seychelles.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (155, 1, 'Sierra Leone', '', '/images/sierra_leone.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (156, 1, 'Singapore', '', '/images/singapore.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (157, 1, 'Slovakia', '', '/images/slovakia.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (158, 1, 'Slovenia', '', '/images/slovenia.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (159, 1, 'Solomon Islands', 'Quần đảo Solomon', '/images/solomon_islands.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (160, 1, 'Somalia', '', '/images/somalia.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (161, 1, 'South Africa', 'Nam Phi', '/images/south_africa.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (162, 1, 'South Korea', 'Hàn Quốc', '/images/south_korea.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (163, 1, 'South Sudan', 'Nam Sudan', '/images/south_sudan.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (164, 1, 'Spain', 'Tây Ban Nha', '/images/spain.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (165, 1, 'Sri Lanka', '', '/images/sri_lanka.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (166, 1, 'Sudan', '', '/images/sudan.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (167, 1, 'Suriname', '', '/images/suriname.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (168, 1, 'Sweden', 'Thụy Điển', '/images/sweden.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (169, 1, 'Switzerland', 'Thụy Sỹ', '/images/switzerland.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (170, 1, 'Syria', '', '/images/syria[z].png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (171, 1, 'Tajikistan', '', '/images/tajikistan.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (172, 1, 'Tanzania', '', '/images/tanzania.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (173, 1, 'Thailand', 'Thái Lan', '/images/thailand.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (174, 1, 'Timor-Leste', '', '/images/timor-leste.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (175, 1, 'Togo', '', '/images/togo.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (176, 1, 'Tonga', '', '/images/tonga.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (177, 1, 'Trinidad and Tobago', '', '/images/trinidad_and_tobago.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (178, 1, 'Tunisia', '', '/images/tunisia.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (179, 1, 'Turkey', 'Thổ Nhĩ Kỳ', '/images/turkey.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (180, 1, 'Turkmenistan', '', '/images/turkmenistan.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (181, 1, 'Tuvalu', '', '/images/tuvalu.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (182, 1, 'Uganda', '', '/images/uganda.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (183, 1, 'Ukraine', '', '/images/ukraine.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (184, 1, 'United Arab Emirates', 'Các Tiểu Vương quốc Ả Rập Thống nhất', '/images/united_arab_emirates.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (185, 1, 'United Kingdom', 'Vương quốc Anh', '/images/united_kingdom.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (186, 1, 'United States', 'Hoa Kỳ', '/images/united_states.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (187, 1, 'Uruguay', '', '/images/uruguay.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (188, 1, 'Uzbekistan', '', '/images/uzbekistan.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (189, 1, 'Vanuatu', '', '/images/vanuatu.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (190, 1, 'Vatican City', '', '/images/vatican_city.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (191, 1, 'Venezuela', '', '/images/venezuela.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (192, 1, 'Vietnam', 'Việt Nam', '/images/vietnam.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (193, 1, 'Yemen', 'Yêmen', '/images/yemen.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (194, 1, 'Zambia', '', '/images/zambia.png');
INSERT INTO Items (nation_id, item_type, name_en, name_vi, item_url) VALUES (195, 1, 'Zimbabwe', '', '/images/zimbabwe.png');