INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (1, 'Afghanistan', '', 7);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (2, 'Albania', '', 3);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (3, 'Algeria', '', 1);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (4, 'Andorra', '', 3);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (5, 'Angola', '', 1);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (6, 'Antigua and Barbuda', '', 4);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (7, 'Argentina', '', 5);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (8, 'Armenia', '', 2);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (9, 'Australia', 'Úc', 6);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (10, 'Austria', 'Áo', 3);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (11, 'Azerbaijan', '', 2);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (12, 'The Bahamas', '', 7);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (13, 'Bahrain', '', 2);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (14, 'Bangladesh', '', 2);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (15, 'Barbados', '', 4);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (16, 'Belarus', '', 3);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (17, 'Belgium', 'Bỉ', 3);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (18, 'Belize', '', 4);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (19, 'Benin', '', 1);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (20, 'Bhutan', '', 2);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (21, 'Bolivia', '', 5);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (22, 'Bosnia and Herzegovina', '', 3);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (23, 'Botswana', '', 1);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (24, 'Brazil', '', 5);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (25, 'Brunei', '', 7);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (26, 'Bulgaria', '', 3);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (27, 'Burkina Faso', '', 1);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (28, 'Burundi', '', 1);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (29, 'Cambodia', 'Campuchia', 2);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (30, 'Cameroon', '', 1);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (31, 'Canada', '', 4);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (32, 'Cape Verde', '', 7);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (33, 'Central African Republic', 'Cộng hòa Trung Phi', 1);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (34, 'Chad', '', 1);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (35, 'Chile', '', 5);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (36, 'China', 'Trung Quốc', 2);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (37, 'Colombia', '', 5);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (38, 'Comoros', '', 1);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (39, 'Democratic Republic of the Congo', 'Cộng hòa Dân chủ Congo', 7);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (40, 'Republic of the Congo', 'Cộng hòa Congo', 1);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (41, 'Costa Rica', '', 4);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (42, 'Croatia', '', 3);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (43, 'Cuba', '', 4);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (44, 'Cyprus', 'Síp', 2);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (45, 'Czech Republic', 'Cộng hòa Séc', 3);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (46, 'Denmark', 'Đan Mạch', 7);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (47, 'Djibouti', '', 1);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (48, 'Dominica', '', 4);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (49, 'Dominican Republic', 'Cộng hòa Dominica', 4);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (50, 'Ecuador', '', 5);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (51, 'Egypt', 'Ai Cập', 1);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (52, 'El Salvador', '', 4);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (53, 'Equatorial Guinea', '', 1);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (54, 'Eritrea', '', 1);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (55, 'Estonia', '', 3);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (56, 'Eswatini', '', 1);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (57, 'Ethiopia', '', 1);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (58, 'Fiji', '', 6);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (59, 'Finland', 'Phần Lan', 3);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (60, 'France', 'Pháp', 3);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (61, 'Gabon', '', 1);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (62, 'The Gambia', '', 7);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (63, 'Georgia', '', 2);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (64, 'Germany', 'Đức', 3);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (65, 'Ghana', '', 1);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (66, 'Greece', 'Hy Lạp', 3);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (67, 'Grenada', '', 4);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (68, 'Guatemala', '', 4);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (69, 'Guinea', '', 1);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (70, 'Guinea-Bissau', '', 1);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (71, 'Guyana', '', 5);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (72, 'Haiti', '', 4);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (73, 'Honduras', '', 4);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (74, 'Hungary', '', 3);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (75, 'Iceland', '', 3);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (76, 'India', 'Ấn Độ', 2);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (77, 'Indonesia', '', 2);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (78, 'Iran', '', 2);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (79, 'Iraq', '', 2);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (80, 'Ireland', '', 3);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (81, 'Israel', '', 2);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (82, 'Italy', 'Ý', 3);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (83, 'Ivory Coast', 'Bờ Biển Ngà', 7);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (84, 'Jamaica', '', 4);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (85, 'Japan', 'Nhật Bản', 2);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (86, 'Jordan', '', 2);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (87, 'Kazakhstan', '', 2);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (88, 'Kenya', '', 1);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (89, 'Kiribati', '', 6);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (90, 'Kuwait', '', 2);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (91, 'Kyrgyzstan', '', 2);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (92, 'Laos', 'Lào', 2);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (93, 'Latvia', '', 3);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (94, 'Lebanon', '', 2);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (95, 'Lesotho', '', 1);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (96, 'Liberia', '', 1);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (97, 'Libya', '', 1);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (98, 'Liechtenstein', '', 3);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (99, 'Lithuania', '', 3);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (100, 'Luxembourg', '', 3);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (101, 'Madagascar', '', 1);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (102, 'Malawi', '', 1);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (103, 'Malaysia', '', 2);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (104, 'Maldives', '', 2);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (105, 'Mali', '', 1);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (106, 'Malta', '', 3);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (107, 'Marshall Islands', 'Quần đảo Marshall', 6);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (108, 'Mauritania', '', 1);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (109, 'Mauritius', '', 1);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (110, 'Mexico', '', 4);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (111, 'Micronesia', '', 7);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (112, 'Moldova', '', 3);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (113, 'Monaco', '', 3);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (114, 'Mongolia', 'Mông Cổ', 2);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (115, 'Montenegro', '', 3);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (116, 'Morocco', 'Ma-rốc', 1);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (117, 'Mozambique', '', 1);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (118, 'Myanmar', '', 2);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (119, 'Namibia', '', 1);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (120, 'Nauru', '', 6);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (121, 'Nepal', '', 2);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (122, 'Netherlands', 'Hà Lan', 3);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (123, 'New Zealand', '', 6);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (124, 'Nicaragua', '', 4);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (125, 'Niger', '', 1);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (126, 'Nigeria', '', 1);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (127, 'North Korea', 'Bắc Triều Tiên', 2);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (128, 'North Macedonia', 'Bắc Macedonia', 3);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (129, 'Norway', 'Na Uy', 3);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (130, 'Oman', '', 2);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (131, 'Pakistan', '', 2);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (132, 'Palau', '', 6);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (133, 'Palestine', '', 7);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (134, 'Panama', '', 4);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (135, 'Papua New Guinea', '', 6);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (136, 'Paraguay', '', 5);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (137, 'Peru', '', 5);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (138, 'Philippines', '', 2);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (139, 'Poland', 'Ba Lan', 3);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (140, 'Portugal', 'Bồ Đào Nha', 3);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (141, 'Qatar', '', 2);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (142, 'Romania', '', 3);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (143, 'Russia', 'Nga', 7);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (144, 'Rwanda', '', 1);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (145, 'Saint Kitts and Nevis', '', 4);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (146, 'Saint Lucia', '', 4);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (147, 'Saint Vincent and the Grenadines', '', 4);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (148, 'Samoa', '', 6);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (149, 'San Marino', '', 3);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (150, 'São Tomé and Príncipe', '', 7);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (151, 'Saudi Arabia', 'Ả-Rập Xê-út', 2);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (152, 'Senegal', '', 1);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (153, 'Serbia', '', 3);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (154, 'Seychelles', '', 1);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (155, 'Sierra Leone', '', 1);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (156, 'Singapore', '', 2);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (157, 'Slovakia', '', 3);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (158, 'Slovenia', '', 3);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (159, 'Solomon Islands', 'Quần đảo Solomon', 6);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (160, 'Somalia', '', 1);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (161, 'South Africa', 'Nam Phi', 1);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (162, 'South Korea', 'Hàn Quốc', 2);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (163, 'South Sudan', 'Nam Sudan', 1);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (164, 'Spain', 'Tây Ban Nha', 3);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (165, 'Sri Lanka', '', 2);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (166, 'Sudan', '', 1);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (167, 'Suriname', '', 5);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (168, 'Sweden', 'Thụy Điển', 3);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (169, 'Switzerland', 'Thụy Sỹ', 3);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (170, 'Syria', '', 7);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (171, 'Tajikistan', '', 2);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (172, 'Tanzania', '', 1);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (173, 'Thailand', 'Thái Lan', 2);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (174, 'Timor-Leste', '', 7);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (175, 'Togo', '', 1);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (176, 'Tonga', '', 6);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (177, 'Trinidad and Tobago', '', 4);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (178, 'Tunisia', '', 1);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (179, 'Turkey', 'Thổ Nhĩ Kỳ', 7);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (180, 'Turkmenistan', '', 2);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (181, 'Tuvalu', '', 6);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (182, 'Uganda', '', 1);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (183, 'Ukraine', '', 3);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (184, 'United Arab Emirates', 'Các Tiểu Vương quốc Ả Rập Thống nhất', 2);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (185, 'United Kingdom', 'Vương quốc Anh', 3);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (186, 'United States', 'Hoa Kỳ', 4);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (187, 'Uruguay', '', 5);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (188, 'Uzbekistan', '', 2);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (189, 'Vanuatu', '', 6);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (190, 'Vatican City', '', 7);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (191, 'Venezuela', '', 5);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (192, 'Vietnam', 'Việt Nam', 2);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (193, 'Yemen', 'Yêmen', 2);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (194, 'Zambia', '', 1);
INSERT INTO Nations (id, name_en, name_vi, region_id) VALUES (195, 'Zimbabwe', '', 1);