--Create table and Insert data
-- BE/sql/schema.sql

-- Drop tables if exist (for dev only)
--BEGIN
--  EXECUTE IMMEDIATE 'DROP TABLE Items CASCADE CONSTRAINTS';
--  EXECUTE IMMEDIATE 'DROP TABLE Type CASCADE CONSTRAINTS';
--  EXECUTE IMMEDIATE 'DROP TABLE Nations CASCADE CONSTRAINTS';
--  EXECUTE IMMEDIATE 'DROP TABLE Region CASCADE CONSTRAINTS';
--EXCEPTION
--  WHEN OTHERS THEN NULL;
--END;
--/

CREATE TABLE Region (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  region_name VARCHAR2(100) UNIQUE
);

CREATE TABLE Nations (
  id NUMBER PRIMARY KEY,
  name_en VARCHAR2(100),
  name_vi VARCHAR2(100),
  region_id NUMBER,
  CONSTRAINT fk_nation FOREIGN KEY (region_id) REFERENCES Region(id)
);
-- Type table (flag, flower, animal, landmark, etc.)
CREATE TABLE Type ( 
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type_name VARCHAR2(100)
);
-- Items table (each item is linked to nation and a type)
CREATE TABLE Items ( 
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nation_id NUMBER,
  item_type NUMBER,
  name_en VARCHAR2(100),
  name_vi VARCHAR2(100),
  item_url VARCHAR2(300),
  CONSTRAINT fk_item_nation FOREIGN KEY (nation_id) REFERENCES Nations(id),
  CONSTRAINT fk_item_type FOREIGN KEY (item_type) REFERENCES Type(id)
);

--Insert Data
INSERT INTO Region(region_name) VALUES ('Africa');
INSERT INTO Region(region_name) VALUES ('Asia');
INSERT INTO Region(region_name) VALUES ('Europe');
INSERT INTO Region(region_name) VALUES ('North Americas');
INSERT INTO Region(region_name) VALUES ('South Americas');
INSERT INTO Region(region_name) VALUES ('Oceania');
INSERT INTO Region(region_name) VALUES ('Unknown');

INSERT INTO Type(type_name) VALUES ('flag');
INSERT INTO Type(type_name) VALUES ('flower');
INSERT INTO Type(type_name) VALUES ('animal');
INSERT INTO Type(type_name) VALUES ('landmark');

COMMIT;
